name: CI/CD Pipeline with Email Notification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u rigonnhasani --password-stdin

      - name: Build and push the image
        env:
          IMAGE_NAME: ghcr.io/rigonnhasani/actions-runner-controller:latest
        run: |
          docker build -t $APP_JS .
          docker push $APP_JS
