name: CI/CD Pipeline with Email Notification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u rigonnhasani --password-stdin

      - name: Build and push the image
        env:
          IMAGE_NAME: ghcr.io/rigonnhasani/actions-runner-controller:latest
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.outlook.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "CI/CD Pipeline Execution"
          to: rigonnhasani@outlook.com
          from: github-actions45@gmail.com
          body: "Docker image has been built and pushed successfully."

